Exception: Set Exception message by default
Before, it was possible to get an Exception with a null message.  This
may have only happened because all classes can be created with a default
constructor, though I think that may have actually been fixed upstream
at this point, so this may be of limited value.